# See config.example.yml for documentation.
object_base: orig/GOWE69
object: sys/main.dol
hash: 9619ba57c9919f95f7f2ac951a2166a3517f91e3
symbols: config/GOWE69/symbols.txt
splits: config/GOWE69/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
quick_analysis: true

block_relocations:
# - source: .text:0x800F92C0
#   end: .text:0x800F92C8
# - source: .text:0x800F9368
#   end: .text:0x800F9370

- target: .text:0x80135100
- target: .text:0x80135000
- target: .text:0x80134001
- target: .text:0x80134008
- target: .text:0x80134010
- target: .text:0x80134100
- target: .text:0x80134000
