# See config.example.yml for documentation.
object: orig/EUROPEGERMILESTONE/NfsMWEuropeGerMilestone.xex
hash: e032bccf5a246644b734218e753347cd7c75ac42
symbols: config/EUROPEGERMILESTONE/symbols.txt
splits: config/EUROPEGERMILESTONE/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
quick_analysis: true
